easy_admin:
    site_name: 'Super Tomate'
    # On définit l'affichage de l'utilisateur
    user:
        display_name: true
        display_avatar: false
    design:
        form_theme:
            - "@EasyAdmin/form/bootstrap_4.html.twig"
            - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
        menu:
            - { label: 'Modération' }
            - { entity: 'RecipeModeration', label: 'Recettes', icon: 'book' } 
            - { label: 'Paramètres' }
            - { entity: 'Category', label: 'Catégories', icon: 'tag' }
            - { entity: 'Difficulty', label: 'Difficultés', icon: 'tag' }
            - { entity: 'Tag', label: 'Badges', icon: 'tag' }
            - { entity: 'Highlight', label: 'Mises en avant', icon: 'tag' }
            - { entity: 'RecipeHighlight', label: 'Actu', icon: 'tag' }
            - { label: 'Recettes' }
            - { entity: 'Recipe', label: 'Recettes', icon: 'book' }     
            - { entity: 'Ingredient', label: 'Ingrédients', icon: 'tag' }
            - { entity: 'Step', label: 'Etapes', icon: 'tag' }
            #- { label: 'Utilisateurs' }
            #- { entity: 'User', label: 'Utilisateurs', icon: 'user' }
    formats:
        datetime: 'd/m/Y à H:i'
    entities:
        RecipeModeration:
            class: App\Entity\Recipe
            label: 'Recettes'
            disabled_actions: ['new','search']
            list:
                dql_filter: 'entity.isChecked = false'
                fields:
                    - id
                    - { property: 'name', label: 'Nom' }
                    - { property: 'category', label: 'Catégorie'}
                    - { property: 'difficulty', label: 'Difficulté'}
                    - { property: 'picture', label: 'Image', type: 'image', base_path: '%app.path.pictures%' }
                    - { property: 'createdAt', label: 'Créé' }
                    - { property: 'isChecked', type: 'toggle', label: 'Vérifié' }   
                sort: ['createdAt', 'asc']
            form:
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'category', label: 'Catégorie', type: 'entity', type_options: { class: 'App\Entity\Category' }}
                    - { property: 'difficulty', label: 'Difficulté', type: 'entity', type_options: { class: 'App\Entity\Difficulty' }}
                    - { property: 'serve', label: 'Portion' }
                    - { property: 'making', label: 'Préparation' }
                    - { property: 'cook', label: 'Cuisson' }
                    - { property: 'wait', label: 'Pause' }
                    - { property: 'imageFile', type: 'vich_image', label: 'Image' }
                    - { property: 'tags', label: 'Mots Clés', type: 'entity', type_options: { class: 'App\Entity\Tag', multiple: true,by_reference: false, attr: { data-widget: 'select2' }}}      
                    - { property: 'isChecked', label: 'Vérifié' }
            show:
                fields:
                    - { property: 'name', label: 'Nom' }                
        Category:
            class: App\Entity\Category
            label: 'Catégorie'
            list:
                fields:
                    - id
                    - { property: 'name', label: 'Nom' }
                sort: ['id', 'asc']    
            form:
                fields:        
                    - { property: 'name', label: 'Nom' }
                sort: ['id', 'asc']     
        Difficulty:
            class: App\Entity\Difficulty
            label: 'Difficulté'
            list:
                fields:
                    - id
                    - { property: 'name', label: 'Nom' }
                sort: ['id', 'asc']     
            form:
                fields:        
                    - { property: 'name', label: 'Nom' }
        Tag:
            class: App\Entity\Tag
            label: 'Badge'
            list:
                fields:
                    - id
                    - { property: 'name', label: 'Nom' }
                sort: ['id', 'asc']     
            form:
                fields:        
                    - { property: 'name', label: 'Nom' }
        Highlight:
            class: App\Entity\Highlight
            label: 'Mises en avant'
            list:
                fields:
                    - id
                    - { property: 'title', label: 'Titre' }
                    - { property: 'content', label: 'Contenu' }
                sort: ['id', 'asc']     
            form:
                fields:
                   - { property: 'title', label: 'Titre' }   
                   - { property: 'content', label: 'Contenu', type: 'fos_ckeditor', type_options: { config_name: 'main_config' }}                
        RecipeHighlight:
            class: App\Entity\RecipeHighlight
            label: 'Actu'
            list:
                fields:
                    - id
                    - { property: 'recipe', label: 'Recette' }
                    - { property: 'highlight', label: 'accroche' }
                sort: ['id', 'asc']     
            form:
                fields:        
                    - { property: 'recipe', label: 'Recette', type: 'entity', type_options: { class: 'App\Entity\Recipe' }}
                    - { property: 'highlight', label: 'accroche', type: 'entity', type_options: { class: 'App\Entity\Highlight' }}                                    
        Recipe:
            class: App\Entity\Recipe
            label: 'Recette'
            list:
                fields:
                    - id
                    - { property: 'name', label: 'Nom' }
                    - { property: 'serve', label: 'Portion' }
                    - { property: 'making', label: 'Préparation' }
                    - { property: 'cook', label: 'Cuisson' }
                    - { property: 'wait', label: 'Pause' }
                    - { property: 'category', label: 'Catégorie'}
                    - { property: 'difficulty', label: 'Difficulté'}
                    - { property: 'Tag', label: 'Mots-Clés', type: 'array'}
                    - { property: 'picture', label: 'Image', type: 'image', base_path: '%app.path.pictures%' }
                    - { property: 'createdAt', label: 'Créé' }
                sort: ['createdAt', 'desc']
            form:
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'serve', label: 'Portion' }
                    - { property: 'making', label: 'Préparation' }
                    - { property: 'cook', label: 'Cuisson' }
                    - { property: 'wait', label: 'Pause' }
                    - { property: 'imageFile', type: 'vich_image', label: 'Image' }
                    - user
                    - { property: 'category', label: 'Catégorie', type: 'entity', type_options: { class: 'App\Entity\Category' }}
                    - { property: 'difficulty', label: 'Difficulté', type: 'entity', type_options: { class: 'App\Entity\Difficulty' }}
                    - { property: 'tags', label: 'Mots Clés', type: 'entity', type_options: { class: 'App\Entity\Tag', multiple: true,by_reference: false, attr: { data-widget: 'select2' }}}    
        Ingredient:
            class: App\Entity\Ingredient
            label: 'Ingrédients'
            list:
                fields:
                    - id
                    - { property: 'recipe', label: 'Recette' }
                    - { property: 'rank', label: 'Position' }
                    - { property: 'content', label: 'contenu' }
                sort: ['id', 'asc']     
            form:
                fields:     
                    - { property: 'recipe', label: 'Recette', type: 'entity', type_options: { class: 'App\Entity\Recipe' }}   
                    - { property: 'rank', label: 'Position' }
                    - { property: 'content', label: 'Contenu' } 
        Step:
            class: App\Entity\Step
            label: 'Etapes'
            list:
                fields:
                    - id
                    - { property: 'recipe', label: 'Recette' }
                    - { property: 'rank', label: 'Position' }
                    - { property: 'content', label: 'contenu' }
                sort: ['id', 'asc']     
            form:
                fields:     
                    - { property: 'recipe', label: 'Recette', type: 'entity', type_options: { class: 'App\Entity\Recipe' }}   
                    - { property: 'rank', label: 'Position' }
                    - { property: 'content', label: 'Contenu', type: 'fos_ckeditor', type_options: { config_name: 'main_config' }}            