vich_uploader:
    db_driver: orm

    mappings:
        pictures:
            uri_prefix: "%app.path.pictures%"
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public%app.path.pictures%'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true